# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update", "--no-cache"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
        # Exclude Markdown files because `  ` at the end of a line is a valid
        # syntax to notify a line break.
        # See https://github.com/pre-commit/pre-commit-hooks/issues/57
        exclude_types: [markdown]
        exclude: task_manager/tests/fixtures/expected_pieces_html.py
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude: task_manager/tests/fixtures/expected_pieces_html.py
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
        exclude: task_manager/tests/fixtures/expected_pieces_html.py
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: task_manager/settings.py
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]
        args: [--contrib=CT1, --msg-filename]
  - repo: local
    hooks:
      - id: mypy
        name: run mypy
        language: system
        # entry should be the same you'd use to run mypy locally
        entry: mypy task_manager --config-file pyproject.toml
        pass_filenames: false # not needed, as mypy should be executed on the whole codebase
        always_run: true
        types: [python, pyi]
      - id: htmlformatter
        name: prettier html formatter
        language: node
        additional_dependencies:
          - prettier@3.3.2
          - prettier-plugin-jinja-template@1.4.0
        entry: npx prettier task_manager --write **/*.html
        pass_filenames: false
