name: pre-commit hooks

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Installing poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Installing project dependencies
        run: |
          poetry config virtualenvs.create false
          make install
      - name: Pre-commit hooks
        run: |
          make pre-commit
